version: "3.9"  
services:
  mysql_db:
    container_name: mysql
    image: ekamoto/mysql:1.0
    networks:
      - app-sisaud-network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - type: bind
        source: "${VOLUME_MYSQL}"
        target: /var/lib/mysql
  app:
    container_name: sw3
    image: ekamoto/app:1.0
    networks:
      - app-sisaud-network
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: "${LOGS}"
        target: /usr/src/app/logs
    depends_on:
      - mysql_db
networks:
  app-sisaud-network:
    driver: bridge
